apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
        - name: checkout
          image: kringel/checkout
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: books
            - name: MONGO_URI
              value: 'mongodb://checkout-mongo-srv:27017/checkout'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
            - name: STRIPE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-srv
spec:
  selector:
    app: checkout
  ports:
    - name: checkout
      protocol: TCP
      port: 3000
      targetPort: 3000
