apiVersion: apps/v1
kind: Deployment
metadata:
  name: stationery-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stationery
  template:
    metadata:
      labels:
        app: stationery
    spec:
      containers:
        - name: stationery
          image: kringel/stationery
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: books
            - name: MONGO_URI
              value: 'mongodb://stationery-mongo-srv:27017/stationery'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: stationery-srv
spec:
  selector:
    app: stationery
  ports:
    - name: stationery
      protocol: TCP
      port: 3000
      targetPort: 3000
